### ISSUE TITLE
History Data Endpoint

### ISSUE THREAD

**Issue by tararjawad** [drixie/royaloak#14]
### request format: ?exchange={EXCHANGE}_{symbol}&tf={timeframe}&from={FROM}&to={to}

example: ?exchange=NASDAQ_AAPL&tf=1D&from=1660568058000&to=1660654458000

exchange = Exchange an underscore followed by the ticker of the requested instrument
tf = timeframe required for the candles : 1s,1m,1h,1d

#### Response: array of Bars

Bar is an object with the following fields:

time: number. Amount of milliseconds since Unix epoch start in UTC timezone. time for daily bars is expected to be a trading day (not session start day) at 00:00 UTC. Charting Library adjusts time according to [Session] from SymbolInfo. time for monthly bars is the first trading day of the month without the time part.
open: number. Bar's open value
high: number. Bar's high value
low: number. Bar's low value
close: number. Bar's close value
volume: number. Bar's volume value

Example bar:
{
close: 1189.8
high: 1197
low: 1116.5
open: 1125.5
time: 1660568058000
volume: 22159225.71
}

**Comment by rylorin** [comment]
+ 5 mins 15 mins 8 hours

**Comment by drixie** [comment]
Timeframes required: 1s, 1m, 5m, 15m, 30m, 1h, 8h, 1d
